mkdir: don't interrupt when error happened (#18195)
## Description
This pr makes mkdir handle all non-error conditions through completion.

## User-facing changes (Release notes)
### mkdir will try to create all directories, even if errors happened in
the middle
```
# Assume you are inside `/tmp` directory
> mkdir a
> chmod 400 a
> mkdir b a/c
Error: nu::shell::error

  × Permission denied
   ╭─[repl_entry #24:1:9]
 1 │ mkdir b a/c
   ·         ─┬─
   ·          ╰── Permission denied
   ╰────
> "b" | path exists
true
```
Also noted that the errors are pointed to correct span. Previously it
points to `crates/nu-command/src/filesystem/umkdir.rs:95:48`, which is
not user friendly.

## Additional notes
related: #15413