rm: returns structure data when -v is used, and don't interrupt when error happened (#18202)
## Description
As title, this pr going to make `rm` works consistently with `mkdir`,
which is changed in https://github.com/nushell/nushell/pull/18195

To implement this, I need to change early return logic on error case,
for any lines returns an Err early, it invokes `collect_rm_result`
closure instead, which pushes result to `verbose_out` if `verbose` is
set, and may set `first_error` variable if rm results to error.

Finally instead of returning `Pipeline::empty`, it may return:
- Pipeline::value(Value::list(verbose_out)) if verbose is set
- Error if verbose is not set and there is an error
- Pipeline::empty

## User-facing changes (Release notes)
### `rm -v` returns structured data
```
> rm -v z a c
╭───┬────────┬─────────┬───────────╮
│ # │  path  │ deleted │   error   │
├───┼────────┼─────────┼───────────┤
│ 0 │ /tmp/z │ false   │ Not found │
│ 1 │ /tmp/c │ false   │ Not found │
│ 2 │ /tmp/a │ true    │           │
╰───┴────────┴─────────┴───────────╯
```
### `rm` removes other files even if there is an error in the middle
```
> touch a
> rm z c a
Error: nu::shell::io::not_found

  × Not found
   ╭─[repl_entry #7:1:6]
 1 │ rm z c a
   ·      ┬
   ·      ╰── Not found
   ╰────
  help: '/tmp/c' does not exist

Error: nu::shell::io::not_found

  × Not found
   ╭─[repl_entry #7:1:4]
 1 │ rm z c a
   ·    ┬
   ·    ╰── Not found
   ╰────
  help: '/tmp/z' does not exist
> 'a' | path exists
false
```

## Additional notes
- related: https://github.com/nushell/nushell/issues/15413